mathjax_plugin:
  enable_mathjax_plugin:
    client: true
    default: false
  mathjax_url:
    client: true
    default: //cdn.mathjax.org/mathjax/latest/MathJax.js
  mathjax_config:
    client: true
    default: TeX-AMS-MML_HTMLorMML
